// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcqwbclyjglgiggguxyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jcXdiY2x5amdsZ2lnZ2d1eHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzI1MDEsImV4cCI6MjA3MDg0ODUwMX0._WYf6azv0CyZQIOHg_iARTWnJthql8BVP3CRla2LcDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});